app:
  hostname: app
  build: .
  ports:
   - '8080:8080'
  links:
   - db
  volumes:
   - .:/src
web:
  hostname: web
  image: httpd
  ports:
   - '9080:80'
  volumes:
   - .:/src
  links:
   - app
db:
  hostname: db
  image: mysql/mysql-server
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: "true"
  ports:
   - '3306:3306'
  volumes:
   - .:/src
