php:
  image: "${app}"
  ports:
    - '9000:9000'
  volumes:
    - './volumes/app:/var/www/app:ro'
  environment:
    DOCUMENT_ROOT: '/var/www/app'
php-fcgi:
  image: 'braucher/fcgi'
  ports:
    - '80:80'
    - '443:443'
  links:
    - "${app}"
  volumes:
    - './volumes/app:/var/www/app:ro'
  environment:
    DOCUMENT_ROOT: '/var/www/app'
    PROXY_TARGET: "${app}:9000"
    DIRECTORY_INDEX: 'index.php'
    FILES_MATCH: '\.php$$'

