php:
  build: app
  ports:
    - '9000:9000'
  volumes:
    - './volumes/app:/var/www/app'
    - './volumes/export:/export'
  command: "${command}"
  environment:
    DB_HOST: "${app}-db"
    DOCUMENT_ROOT: '/var/www/app'
php-web:
  image: 'braucher/fcgi'
  ports:
    - '80:80'
    - '443:443'
  links:
    - "${app}"
  volumes:
    - './volumes/app:/var/www/app:ro'
  environment:
    PROXY_TARGET: "${app}:9000"
    DOCUMENT_ROOT: '/var/www/app'
    DIRECTORY_INDEX: 'index.php'
    FILES_MATCH: '\.php$$'

