php:
  image: "${app}"
  ports:
    - '9000:9000'
  links:
    - "${app}-db"
  volumes:
    - './volumes/app:/var/www/app'
    - './volumes/export:/export'
  command: "${command}"
  environment:
    DB_HOST: "${app}-db"
    DOCUMENT_ROOT: '/var/www/app'
php-db:
  image: 'mysql:5.6'
  volumes:
    - '/var/lib/mysql'
  environment:
    MYSQL_ROOT_PASSWORD: "root_66_${app}"
    MYSQL_DATABASE: "${app}"
    MYSQL_USER: "${app}"
    MYSQL_PASSWORD: "password4${app}"
php-web:
  image: 'braucher/fcgi'
  ports:
    - '80:80'
    - '443:443'
  links:
    - "${app}"
  volumes:
    - './volumes/app:/var/www/app:ro'
    - './volumes/export:/export'
  environment:
    PROXY_TARGET: "${app}:9000"
    DOCUMENT_ROOT: '/var/www/app'
    DIRECTORY_INDEX: 'index.php'
    FILES_MATCH: '\.php$$'

